### ISSUE TITLE
Route::currentRouteName() for Laravel Folio named route returns 'laravel-folio'

### ISSUE THREAD

**Issue by richeklein** [laravel/folio#89]
### Folio Version

v1.0.0-beta.6

### Laravel Version

10.19.0

### PHP Version

8.2.3

### Description

When using a named route in Laravel Folio the `Route::currentRouteName()` function returns "laravel-folio" instead of the route name defined in the `name` function. I'm not sure if this is required for Folio's magic or just unintended.

### Steps To Reproduce

1. create a new Folio page
2. add a name — e.g. `name('about')`
3. the output of `Route::currentRouteName()` equals "laravel-folio" instead of "about"

**Comment by hazwan91** [comment]
I also have the same problem when checking if my current nav-item is active using `request()->routeIs('dashboard.index')` and it always return false since the current route name keeps giving me `laravel-folio` as the OP said.

![Screenshot 2023-08-21 132325](https://github.com/laravel/folio/assets/97268905/a87b755b-d89b-46f7-94f9-0a8cd0e8e8c4)

Currently i have to use `request()->is('dashboard')` to determine my current page which indicates my folder/file name.

**Comment by jdion84** [comment]
Routes seem to always use the fallback name, guessing it's something to do with the service provider lifecycle or something.

```php
Route::fallback($this->handler())->name('laravel-folio');
```
